File tesbed (IRS +  EKSS part)
ghga-de/file-stack-test-bed pull request #1
Opened 2022-11-30 11:07 UTC by mephenor

Adjusted the test action a bit, so this runs inside the devcontainer spinnig up all containers in the docker-compose.
Two issues exist currently, which we should fix when extending this to other services:

 - IRS container currently always restarts to deal with Kafka startup. This might mask other issues. This should be done by a healthcheck instead, though I could not yet figure out how to make it work. A variant of the `wait_for_it` script might also be a valid solution.
 
 - Dummy secrets are currently hardcoded. Might be better to inject them from somewhere else.
 
 ```
 Created docker-compose for local file testbed, covering IRS and EKSS for now (GDEV-1420)
 Added simple testcase to check processing of events through the stack (GDEV-1421)
 
 Co-authored-by: Moritz Hahn <Moritz.Hahn@uni-tuebingen.de>
 Co-authored-by: Kersten Breuer <kersten-breuer@outlook.com>
 ```

2022-11-30 13:16 UTC, KerstenBreuer requested changes
Looks good, maybe we can discuss the tests later.

2022-11-30 13:16 UTC, KerstenBreuer commented on tests/fixtures/local_fixtures.py
> +    """Fields from recorded event that hold values that can an should be checked"""
```suggestion
    """Fields from recorded event that hold values that can and should be checked"""
```

2022-11-30 13:16 UTC, KerstenBreuer commented on tests/fixtures/config.py
> +class Config(BaseSettings):
We can also inherit from hexkits S3Config and KafkaConfig

2022-11-30 13:16 UTC, KerstenBreuer commented on tests/fixtures/local_fixtures.py
> +async def populated_bucket_fixture(
Some of the test logic is here in the fixtures, however, the fixtures should only setup and teardown state required for the test to run.

2022-11-30 13:16 UTC, KerstenBreuer commented on tests/fixtures/local_fixtures.py
> +            )
You cannot guarantee interrogation results will already be available when the event recorder stops.

2022-11-30 14:21 UTC, MoritzHahn1337 approved these changes

2022-11-30 14:21 UTC, MoritzHahn1337 commented on tests/fixtures/local_fixtures.py
> +    """Fields from recorded event that hold values that can an should be checked"""
```suggestion
    """Fields from recorded event that hold values that can and should be checked"""
```

2022-12-01 08:43 UTC, MoritzHahn1337 approved these changes

2022-12-01 11:05 UTC, MoritzHahn1337 approved these changes

2022-12-01 15:16 UTC, KerstenBreuer approved these changes

2022-12-01 15:16 UTC, KerstenBreuer commented on .devcontainer/docker-compose.yml
> +    healthcheck:
Nice

2022-12-01 16:46 UTC, merged